name: ArchangelVPN_AutoUpdate

on:
  schedule:
    - cron: '0 */3 * * *' # Обновление каждые 3 часа
  workflow_dispatch: # Кнопка для ручного запуска в Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешаем запись в репозиторий
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scraper
        run: python parser.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add sub.txt index.html
          git commit -m "Auto-update nodes: $(date)" || exit 0
          git push